spring:
  application:
    name: mcp-server

# Server Configuration
server:
  port: 8103

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    snvn.mcpserver: DEBUG


