spring:
  profiles:
    active: dev
  application:
    name: user-service


server:
  port: 8102

# #Splunk HEC Configuration
#splunk:
#  hec:
#    url: https://localhost:8088/services/collector
#    token: a22e99ae-51de-4bff-8567-a726b83760d6
#    index: main
#    source: user-service
#    sourcetype: _json
#    enabled: true
#    batch-size: 100
#    flush-interval: 5000
#    ssl-verify: false


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

#logging:
#  level:
#    root: INFO
#    snvn: DEBUG
#    org.springframework.web: INFO
#    org.hibernate.SQL: WARN
#
#  file:
#    name: logs/${spring.application.name}.log
#
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      max-history: 30
#      total-size-cap: 2GB
#
#  pattern:
#    console: >
#      {"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSS}",
#       "level":"%level",
#       "service":"${spring.application.name}",
#       "thread":"%thread",
#       "traceId":"%X{traceId:-}",
#       "spanId":"%X{spanId:-}",
#       "correlationId":"%X{correlationId:-}",
#       "jobId":"%X{jobId:-}",
#       "logger":"%logger{36}",
#       "message":"%msg",
#       "exception":"%replace(%ex){'\n','\\\\n'}"}%n
#
#    file: >
#      {"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSS}",
#       "level":"%level",
#       "service":"${spring.application.name}",
#       "thread":"%thread",
#       "traceId":"%X{traceId:-}",
#       "spanId":"%X{spanId:-}",
#       "correlationId":"%X{correlationId:-}",
#       "jobId":"%X{jobId:-}",
#       "logger":"%logger{36}",
#       "message":"%msg",
#       "exception":"%replace(%ex){'\n','\\\\n'}"}%n

splunk:
  hec:
    source: user-service

user-service:
   redis-rate-limiting:
     enabled: true

grpc:
  server:
    port: 9091